SELECT C.AUTHOR_ID, C.AUTHOR_NAME,B.CATEGORY, SUM(A.TOTAL_SALE * B.PRICE) AS TOTAL_SALES
FROM (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALE 
    FROM BOOK_SALES 
    WHERE SALES_DATE >= '2022-01-01' AND SALES_DATE <='2022-01-31'
    GROUP BY BOOK_ID
) AS A
JOIN BOOK AS B ON A.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS C ON C.AUTHOR_ID= B.AUTHOR_ID
GROUP BY C.AUTHOR_ID, C.AUTHOR_NAME,B.CATEGORY
ORDER BY C.AUTHOR_ID, B.CATEGORY DESC





