SELECT A.CART_ID
FROM (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt' OR NAME = 'Milk'
    GROUP BY CART_ID, NAME
) AS A
GROUP BY A.CART_ID
HAVING COUNT(DISTINCT A.NAME) >= 2