-- 코드를 입력하세요
# SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, 
#         RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE),3) as SCORE
#     from REST_INFO as RI
#     left join REST_REVIEW  as RR on RI.REST_ID = RR.REST_ID
#     where RI.ADDRESS LIKE '서울%' and RR.REVIEW_SCORE is not null
#     group by RI.REST_ID
#     order by SCORE desc, RI.PARKING_LOT desc
    
    
    
SELECT RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE, RI.FAVORITES, RI.ADDRESS, ROUND(AVG(RR.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW RR
LEFT JOIN REST_INFO RI
ON RR.REST_ID = RI.REST_ID
GROUP BY RR.REST_ID
HAVING RI.ADDRESS LIKE "서울%"
ORDER BY SCORE DESC, RI.FAVORITES DESC