SELECT A.PRODUCT_ID, B.PRODUCT_NAME, (A.TOTAL_AMOUNT * B.PRICE) AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID,SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE >= '2022-05-01' AND PRODUCE_DATE<= '2022-05-31'
    GROUP BY PRODUCT_ID 
) AS A
LEFT JOIN FOOD_PRODUCT AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID



    
 