SELECT CONCAT("/home/grep/src/",UF.BOARD_ID,"/",UF.FILE_ID,UF.FILE_NAME,UF.FILE_EXT) AS FILE_PATH
FROM (
    SELECT *
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) AS UB 
LEFT JOIN USED_GOODS_FILE AS UF ON UB.BOARD_ID = UF.BOARD_ID
ORDER BY UF.FILE_ID DESC;
